all:
  children:
    control-plane:
      hosts:
        control-plane-0.k8s.cluster:
          ansible_host: 192.168.0.200
    worker-nodes:
      hosts:
        worker-0.k8s.cluster:
          ansible_host: 192.168.0.210
        worker-1.k8s.cluster:
          ansible_host: 192.168.0.211
        worker-2.k8s.cluster:
          ansible_host: 192.168.0.212
